### ISSUE TITLE
json deprecation

### ISSUE THREAD

**Issue by ksIsCute** [rtk-rnjn/Parrot#209]
**Describe the bug**
a bug that can possibly crash the bot

**To Reproduce**
1. run a json command
2. if any args, make them U+1F600, the bot explodes.

**Expected behavior**
get json information with no errors and little latency

**Comment by rtk-rnjn** [comment]
Well, you better be right. For now it works. You mentioned the issue, please tell the solution as well.

**Comment by ksIsCute** [comment]
problem is whatever you try and do wont fix it, its either an API bug, or a discord.py bug. but because of discord.py's unfortunate discontinuation, its impossible to fix unless you fork discord.py, and fix it yourself in the __init__ file.
